spring.application.name=backend

spring.datasource.url=jdbc:postgresql://localhost:5432/fashionsense
spring.datasource.username=fashionsense
spring.datasource.password=${POSTGRES_PASSWORD}

spring.jpa.hibernate.ddl-auto=none
spring.jpa.open-in-view=false

app.jwt.secret=${JWT_SECRET}
app.jwt.expiration-minutes=60

app.email-verification.expiration-minutes=1440

# Redis
spring.data.redis.host=localhost
spring.data.redis.port=6379

# Spring Cache
spring.cache.type=redis
spring.cache.cache-names=productDetails
spring.cache.redis.time-to-live=10m
spring.cache.redis.cache-null-values=false
spring.cache.redis.use-key-prefix=true