spring.application.name=backend

spring.datasource.url=jdbc:postgresql://localhost:5432/fashionsense
spring.datasource.username=fashionsense
spring.datasource.password=${POSTGRES_PASSWORD}

spring.jpa.hibernate.ddl-auto=none
spring.jpa.open-in-view=false

app.jwt.secret=${JWT_SECRET}
app.jwt.expiration-minutes=60

app.email-verification.expiration-minutes=1440